language: c
addons:
  apt:
    packages:
      - libsqlite3-dev
      - tcl
services:
  - redis-server
install:
  - ./vagrant/install-jimtcl.sh
before_script:
  - export PATH="$PATH:$PWD/jimtcl"
script:
  - ./tests.tcl
  - tclsh tests.tcl
