language: c
addons:
  apt:
    packages:
      - tcl
services:
  - redis-server
install:
  - wget -O jimsh-0.76 https://github.com/dbohdan/jimsh-static/releases/download/v1/jimsh-0.76-51f65c6d38-i386
  - wget -O jimsh-0.77 https://github.com/dbohdan/jimsh-static/releases/download/v1/jimsh-0.77-a9bf5975fd-i386
  - wget -O jimsh-0.78 https://github.com/dbohdan/jimsh-static/releases/download/v1/jimsh-0.78-022f902632-i386
  - wget -O jimsh-0.79 https://github.com/dbohdan/jimsh-static/releases/download/v2/jimsh-0.79-0aa0fb4e3a-amd64
  - chmod +x jimsh*
before_script:
  - export PATH="$PATH:$PWD/jimtcl"
script:
  - ./jimsh-0.76 tests.tcl
  - ./jimsh-0.77 tests.tcl
  - ./jimsh-0.78 tests.tcl
  - ./jimsh-0.79 tests.tcl
  - tclsh tests.tcl
